name: Deploy to Azure

on:
  workflow_call:
    inputs:
      applicationName:
        required: true
        type: string
      aspnetcoreEnvironment:
        required: true
        type: string
      environment:
        required: true
        type: string
      location:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      SQL_ADMIN_PASSWORD:
        required: true

jobs:
  run-deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out source code
      - name: Check out source code
        uses: actions/checkout@v4

      # Step 2: Download the build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: allyourgoods-api-build
          path: ./allyourgoods-api-build

      # Step 3: Log in to Azure using the credentials from GitHub Secrets
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Construct the resource group name
      - name: Construct Resource Group Name
        run: |
          RESOURCE_GROUP_NAME="${{ inputs.applicationName }}-${{ inputs.environment }}-${{ inputs.location }}-rg"
          echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV

      # Step 5: Create the resource group (if it doesn't exist)
      - name: Create Resource Group
        run: |
          az group create --name $RESOURCE_GROUP_NAME --location ${{ inputs.location }}

      # Step 6: Deploy ARM Template
      - name: Deploy ARM Template
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP_NAME \
            --template-file Infrastructure/azure-deploy.json \
            --parameters appName=${{ inputs.applicationName }} \
                         environment=${{ inputs.environment }} \
                         location=${{ inputs.location }} \
                         sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD }}" \
                         aspnetcoreEnvironment=${{ inputs.aspnetcoreEnvironment }} \

      # Step 7: Deploy the artifact to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.applicationName }}-${{ inputs.environment }}-app
          package: ./allyourgoods-api-build/publish-output.zip