name: Build and Test

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string

jobs:
  run-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test Unit Tests
        run: dotnet test Tests/AllYourGoods.Api.UnitTests/AllYourGoods.Api.UnitTests.csproj --no-build --verbosity normal

      - name: Test Integration Tests
        run: dotnet test Tests/AllYourGoods.Api.IntegrationTests/AllYourGoods.Api.IntegrationTests.csproj --no-build --verbosity normal
     
      - name: Publish Application
        run: dotnet publish Assemblies/AllYourGoods.Api/AllYourGoods.Api.csproj -c Release -o publish-output

      - name: Zip Publish Output
        run: |
          cd publish-output
          zip -r ../publish-output.zip ./*
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allyourgoods-api-build
          path: publish-output.zip